title: Xinrui Zhang's homepage
page-top-title: Back to top
top-section-bg-text: Welcome!
home-subtitle: Xinrui Zhang&ensp;|&ensp;张心睿
copyright-text: '&copy; Xinrui Zhang 2025-2026. All Rights Reserved.'
biography-subtitle: Personal Biography
achievements-subtitle: Achievements & Honors
gallery-subtitle: Photo Gallery
contact-subtitle: Get In Touch